Update to work with thermostat-ng/agent based on openjdk-8-64bit-maven image.

diff --git a/bin/run-thermostat-agent b/bin/run-thermostat-agent
--- a/bin/run-thermostat-agent
+++ b/bin/run-thermostat-agent
@@ -1,27 +1,31 @@
 #!/bin/bash
-if [ ! -e "${USER_THERMOSTAT_HOME}/etc" ]; then
+if [ ! -d "${USER_THERMOSTAT_HOME}/etc" ]; then
   mkdir -p "${USER_THERMOSTAT_HOME}/etc"
 fi
-# Require the following environment variables:
-# - THERMOSTAT_AGENT_USERNAME
-# - THERMOSTAT_AGENT_PASSWORD
-# - THERMOSTAT_DB_URL
-if [ "${THERMOSTAT_AGENT_USERNAME}_" == "_" ]; then
-   echo 1>&2 "Required environment variable THERMOSTAT_AGENT_USERNAME not set"
-   exit 1
-fi
-if [ "${THERMOSTAT_AGENT_PASSWORD}_" == "_" ]; then
-   echo 1>&2 "Required environment variable THERMOSTAT_AGENT_PASSWORD not set"
-   exit 1
-fi
-if [ "${THERMOSTAT_DB_URL}_" == "_" ]; then
-   echo 1>&2 "Required environment variable THERMOSTAT_DB_URL not set"
-   exit 1
-fi
 
-# Set the agent connect credentials
-echo -en "username=${THERMOSTAT_AGENT_USERNAME}\npassword=${THERMOSTAT_AGENT_PASSWORD}\n" > "${USER_THERMOSTAT_HOME}/etc/agent.auth"
-# Set up the command channel server to listen on
-# the specified address and port.
-sed "s%CONFIG_LISTEN_ADDRESS=.*%CONFIG_LISTEN_ADDRESS=0.0.0.0:${THERMOSTAT_CMDC_PORT}%g" ${THERMOSTAT_HOME}/etc/agent.properties > ${USER_THERMOSTAT_HOME}/etc/agent.properties
-${THERMOSTAT_HOME}/bin/thermostat agent -d ${THERMOSTAT_DB_URL}
+plugins="vm-gc vm-memory"
+for plugin in ${plugins}; do
+  prop_file=${THERMOSTAT_HOME}/etc/plugins.d/${plugin}/gateway.properties
+  if [ ! -e "${prop_file}" ]; then
+    echo 1>&2 "Properties file for ${plugin} is missing. This script is out-of-date!"
+    exit 1
+  fi
+  user_prop_dir=${USER_THERMOSTAT_HOME}/etc/plugins.d/${plugin}
+  if [ ! -d "${user_prop_dir}" ]; then
+    mkdir -p "${user_prop_dir}"
+  fi
+  user_prop_file="${user_prop_dir}"/gateway.properties
+
+  # Derive config environment variable from plugin name
+  url_var="THERMOSTAT_$(echo ${plugin} | tr '[:lower:]-' '[:upper:]_')_URL"
+  if [ -z "${!url_var}" ]; then
+    echo 1>&2 "Required environment variable ${url_var} not set"
+    exit 1
+  fi
+
+  # Replace default URL with value of environment variable
+  sed "s|gatewayURL=.*|gatewayURL=${!url_var}|" "${prop_file}" > "${user_prop_file}"
+done
+
+# Run the agent
+${THERMOSTAT_HOME}/bin/thermostat agent
